"""
Curated therapeutic YouTube video catalog for elderly mental wellness.

Single responsibility: static data only — no logic, no imports.
Each entry: youtube_video_id, title, type.
"""
from typing import Final

VideoEntry = dict[str, str]

EMOTION_VIDEO_CATALOG: Final[dict[str, list[VideoEntry]]] = {
    "Happy": [
        {"youtube_video_id": "Yz9REy9ytBo", "title": "Open Yourself to Good Vibes (Guided Meditation)", "type": "meditation"},
        {"youtube_video_id": "j734gLbQFbU", "title": "5 Minute Guided Morning Meditation for Positive Energy", "type": "meditation"},
        {"youtube_video_id": "NNjlpAoKxZ4", "title": "Happy 2025 New Age Music - Positive Meditation", "type": "music"},
        {"youtube_video_id": "w6VQCKgePoA", "title": "4-minute Guided Meditation for Gratitude", "type": "meditation"},
        {"youtube_video_id": "FGO8IWiusJo", "title": "Guided Morning Meditation 10 Minutes Start Day Perfectly", "type": "meditation"},
        {"youtube_video_id": "z6X5oEIg6Ak", "title": "Peaceful Morning Meditation", "type": "meditation"},
        {"youtube_video_id": "qH0zNiCgO9o", "title": "Beautiful Nature Relaxation", "type": "nature"},
        {"youtube_video_id": "1ZYbU82GVz4", "title": "Uplifting Piano Music", "type": "music"},
        {"youtube_video_id": "aEqlQvczMJQ", "title": "Gratitude Meditation", "type": "meditation"},
        {"youtube_video_id": "lFcSrYw-ARY", "title": "Gentle Forest Sounds", "type": "nature"},
        {"youtube_video_id": "xfD4HaBBc0I", "title": "Gratitude Meditation 21 Day Transformation 432 HZ", "type": "meditation"},
        {"youtube_video_id": "txkYVfpTdGA", "title": "Healing Scriptures - Bird Song", "type": "nature"},
        {"youtube_video_id": "oPxkTfmPj3s", "title": "Spring Mountain Forest Birdsong Relaxation", "type": "nature"},
        {"youtube_video_id": "AKy6Jx59fis", "title": "12 Hours of Relaxing Music - Piano with Bird Sounds", "type": "music"},
        {"youtube_video_id": "2OEL4P1Rz04", "title": "Calm Instrumental Music", "type": "music"},
        {"youtube_video_id": "Okehyq5qCSk", "title": "Hosla Happiness Session Minimize Mental Stress", "type": "meditation"},
        {"youtube_video_id": "0SqQkvUV7Vo", "title": "Guided Mindfulness Meditation Positive Thinking Affirmations", "type": "meditation"},
        {"youtube_video_id": "qANaxInPFh0", "title": "5 min Morning Affirmation Meditation Positive Thoughts", "type": "meditation"},
        {"youtube_video_id": "ECHxnCJYrpM", "title": "Powerful Meditation Mind Consciousness Gurudev", "type": "meditation"},
        {"youtube_video_id": "dq-j5ZXQ57M", "title": "Shri Mahalaxmi Morning Meditation Spiritual Growth", "type": "meditation"},
        {"youtube_video_id": "7weBZ4OX0io", "title": "Positive and Powerful Affirmations for 2025", "type": "meditation"},
        {"youtube_video_id": "ZmdTSYMoMAw", "title": "15 Life-Changing Morning Affirmations Happiness Joy", "type": "meditation"},
        {"youtube_video_id": "Pb49bScgR0g", "title": "10-Minute Morning Joy Meditation", "type": "meditation"},
        {"youtube_video_id": "IuqLsYd-rQs", "title": "5 Minute Meditation Positive Energy 2025", "type": "meditation"},
        {"youtube_video_id": "PThQT1eMEog", "title": "Reiki Music Emotional Physical Healing", "type": "music"},
        {"youtube_video_id": "vCpBSnYBTM0", "title": "7 CHAKRAS HEALING MUSIC Positive Energy", "type": "music"},
        {"youtube_video_id": "-NucSdbeIdY", "title": "Best Meditation for Seniors 10 Minutes Unplug", "type": "meditation"},
        {"youtube_video_id": "QD1bhGneU8Y", "title": "Relaxing Songs for Seniors | Uplifting & Heartfelt Music", "type": "music"},
        {"youtube_video_id": "ZWR_Iwu6zKw", "title": "My heart sounds - music for seniors - instrumental", "type": "music"},
        {"youtube_video_id": "JPeT44ZmxHw", "title": "Generation over 60 - instrumental music - cheerful and inspiring", "type": "music"},
        {"youtube_video_id": "LyIYHVdGpFc", "title": "Singalong Music Group for Seniors | Music from the 40s 50s and 60s", "type": "music"},
        {"youtube_video_id": "cNEQGy27uIA", "title": "Senior Moments! | Oldies but Goldies Funny Fails", "type": "funny"},
        {"youtube_video_id": "uFGD89ZPOWU", "title": "9 Hilarious Things Living Alone Makes Us Do In Old Age", "type": "funny"},
        {"youtube_video_id": "hDZKA7RTg78", "title": "DANCE FITNESS FOR SENIORS, OLDER ADULTS, AND BEGINNERS", "type": "dance"},
        {"youtube_video_id": "7K8vAdPiSj8", "title": "DANCE FITNESS for Older Adults | 28 Minutes | Oldies Songs", "type": "dance"},
        {"youtube_video_id": "BHACKCNDMW8", "title": "3 Hours of Amazing Nature Scenery & Relaxing Music for Stress Relief", "type": "nature"},
        {"youtube_video_id": "8WVXk0Gz66E", "title": "10 Hours of Relaxing Music - Calm Piano & Guitar, Sleep", "type": "music"},
    ],
    "Sad": [
        {"youtube_video_id": "ZToicYcHIOU", "title": "Healing Meditation for Sadness", "type": "meditation"},
        {"youtube_video_id": "bVW8i8q2N9o", "title": "Comforting Ocean Waves", "type": "nature"},
        {"youtube_video_id": "3jWRrafhO7M", "title": "Emotional Healing Music", "type": "music"},
        {"youtube_video_id": "O-6f5wQXSu8", "title": "Self-Compassion Meditation", "type": "meditation"},
        {"youtube_video_id": "cXjLBK43b8M", "title": "Peaceful Rain Sounds", "type": "nature"},
        {"youtube_video_id": "AUXGW6sWYDY", "title": "Gentle Healing Relaxation", "type": "relaxation"},
        {"youtube_video_id": "jGiBBq7dBpk", "title": "10 Hours of Huge Waves Ocean Sounds", "type": "nature"},
        {"youtube_video_id": "jX6kn9_U8qk", "title": "Rain Sounds 10 Hours Sleep Relaxation", "type": "nature"},
        {"youtube_video_id": "c2NmyoXBXmE", "title": "Forest River Waterfall Bird Sounds", "type": "nature"},
        {"youtube_video_id": "HchoJcYNYlU", "title": "Relaxing Waterfall Sounds Sleep 10 Hours", "type": "nature"},
        {"youtube_video_id": "yIQd2Ya0Ziw", "title": "Rainstorm Sounds Deep Sleep 8 Hour", "type": "nature"},
        {"youtube_video_id": "YojwmuZSbJk", "title": "30 Minute Deep Sleep Music Meditation", "type": "music"},
        {"youtube_video_id": "eK1sKpIAtd4", "title": "Compassion Focused Meditation Grief", "type": "meditation"},
        {"youtube_video_id": "V-RMWNf9T04", "title": "I Am Near You Meditations Healing Self Compassion", "type": "meditation"},
        {"youtube_video_id": "lkrnhe4r5_c", "title": "Relaxing Meditation Growing Older", "type": "meditation"},
        {"youtube_video_id": "48VfKbP4PHA", "title": "Light Rain Forest Birdsong Spring Drizzle", "type": "nature"},
        {"youtube_video_id": "jcprGTfC4vc", "title": "Deep Sleep Meditation Overactive Mind", "type": "meditation"},
        {"youtube_video_id": "Rj7M3vh1qJk", "title": "Guided Meditation Loss Grief Sadness", "type": "meditation"},
        {"youtube_video_id": "acE6qVnK0r0", "title": "Sad Emotional Tranquil Music Cello", "type": "music"},
        {"youtube_video_id": "tgCsPbrtKus", "title": "Self Love Meditation Broken Heart", "type": "meditation"},
        {"youtube_video_id": "Xn39veSZINI", "title": "Guided Meditation Cope Grief Heal", "type": "meditation"},
        {"youtube_video_id": "6m2Ma8uX74s", "title": "Healing Sorrow Removal Ultra Relaxing", "type": "music"},
        {"youtube_video_id": "BV2Js_yBAjA", "title": "Guided Meditation Broken Heart 20 Min", "type": "meditation"},
        {"youtube_video_id": "v-l0Tj0PdfM", "title": "Guided Mindfulness Grief Sadness", "type": "meditation"},
        {"youtube_video_id": "OWpsZvOsZDA", "title": "Mindfulness Meditation Reduces Loneliness in Older Adults", "type": "meditation"},
        {"youtube_video_id": "SmMv6GC3Je4", "title": "Overcome Grief & Sadness | Find Consolation & Inner Peace", "type": "music"},
        {"youtube_video_id": "nkFMLakG6iw", "title": "Overcome Anxiety, Grief & Depression | 396 Hz Healing", "type": "music"},
        {"youtube_video_id": "3RUEe97fBP0", "title": "Guided Mindfulness Meditation for Loneliness, Sadness & Depression", "type": "meditation"},
        {"youtube_video_id": "yqKOjo34Cho", "title": "Seniors Stories For Sleep - Inspired Story for Adults", "type": "story"},
        {"youtube_video_id": "e9-qLNwwkmE", "title": "2 Hours of Sad Instrumental Music | Piano, Cello, Violin", "type": "music"},
    ],
    "Angry": [
        {"youtube_video_id": "cEqZthCaMpo", "title": "Calming Meditation for Anger", "type": "meditation"},
        {"youtube_video_id": "UEEsdXn8oG8", "title": "Deep Breathing for Stress Relief", "type": "breathing"},
        {"youtube_video_id": "3bfCvwVXsNs", "title": "Soothing Ocean Therapy", "type": "nature"},
        {"youtube_video_id": "j651_I_T_2E", "title": "Tension Release Music", "type": "music"},
        {"youtube_video_id": "mMMerxh_sVQ", "title": "Progressive Muscle Relaxation", "type": "relaxation"},
        {"youtube_video_id": "wEPc-55-oFE", "title": "Gentle Waterfall Sounds", "type": "nature"},
        {"youtube_video_id": "EhUfVa6jnVI", "title": "5 Simple Breathing Exercises Seniors", "type": "breathing"},
        {"youtube_video_id": "1nZEdqcGVzo", "title": "How to Progressive Muscle Relaxation", "type": "relaxation"},
        {"youtube_video_id": "5q3K-6HvQIk", "title": "Progressive Muscle Relaxation 5 Min", "type": "relaxation"},
        {"youtube_video_id": "2IJUD-e14FY", "title": "Guided Progressive Muscle Relaxation", "type": "relaxation"},
        {"youtube_video_id": "Aq6NVQSlxrw", "title": "Soothing Forest Birds Morning", "type": "nature"},
        {"youtube_video_id": "knO-qkrIv5A", "title": "Anxiety Relief Forest Birds Tones", "type": "nature"},
        {"youtube_video_id": "MW3FtiAUVRw", "title": "Relaxing Forest Stream 4K Water", "type": "nature"},
        {"youtube_video_id": "TQDefR0KsHY", "title": "10 Minute Meditation Anger", "type": "meditation"},
        {"youtube_video_id": "wkse4PPxkk4", "title": "10-Minute Meditation For Anger", "type": "meditation"},
        {"youtube_video_id": "431crMGiyT0", "title": "13 Minute Release Anger", "type": "meditation"},
        {"youtube_video_id": "aybpMwDwMn0", "title": "Meeting Anger with Awareness", "type": "meditation"},
        {"youtube_video_id": "ihO02wUzgkc", "title": "Progressive Muscle Relaxation Training", "type": "relaxation"},
        {"youtube_video_id": "q9FmaoiV3rk", "title": "Tai Chi for Seniors by Mr. Randal Lau", "type": "taichi"},
        {"youtube_video_id": "NM5ll2j4mEk", "title": "Soothing Music To Heal Anger And Depressed Feelings", "type": "music"},
        {"youtube_video_id": "C2Z9dl-X3r0", "title": "Anger Management Meditation Music, Calming Soothing", "type": "music"},
        {"youtube_video_id": "bAHEvMNxDlQ", "title": "3 Hours of Relaxing Music to Refresh and Restore", "type": "music"},
    ],
    "Neutral": [
        {"youtube_video_id": "inpok4MKVLM", "title": "Mindfulness Meditation", "type": "meditation"},
        {"youtube_video_id": "36YnV9STBqc", "title": "Peaceful Nature Scenes", "type": "nature"},
        {"youtube_video_id": "ausxoXBrmWs", "title": "10 Minute Guided Meditation Focus", "type": "meditation"},
        {"youtube_video_id": "Jyy0ra2WcQQ", "title": "Balanced Breathing Practice", "type": "breathing"},
        {"youtube_video_id": "1vx8iUvfyCY", "title": "Gentle Body Scan", "type": "relaxation"},
        {"youtube_video_id": "Rr4suTqhyws", "title": "Body Scan for Relaxation", "type": "relaxation"},
        {"youtube_video_id": "uqtIqCKjkuc", "title": "10 Minute Body Scan Meditation", "type": "relaxation"},
        {"youtube_video_id": "VUjiXcfKBn8", "title": "10 Minute Breathing Meditation", "type": "breathing"},
        {"youtube_video_id": "5mOZMxVKmiY", "title": "Body Scan Mindfulness Short", "type": "relaxation"},
        {"youtube_video_id": "lE6RYpe9IT0", "title": "Relaxing Music Nature Waterfall", "type": "nature"},
        {"youtube_video_id": "HPyu0PGqGkU", "title": "Cozy Reading Nook: Relaxing Ambient Music to Read & Study", "type": "music"},
        {"youtube_video_id": "mIYzp5rcTvU", "title": "Classical Music for Reading - Mozart, Chopin, Debussy", "type": "music"},
        {"youtube_video_id": "PEsxFCa-P6Q", "title": "Gentle 30-Minute Chair Yoga: Ideal for Beginners and Seniors", "type": "yoga"},
        {"youtube_video_id": "tq32Q5cKhkQ", "title": "3 Hours Smooth Jazz Saxophone Instrumental Music", "type": "music"},
        {"youtube_video_id": "IQWOQYxPliY", "title": "Classical Focus | Classical Music for Concentration", "type": "music"},
        {"youtube_video_id": "I77NUYL1kgI", "title": "Wonderful Walking Tours for Seniors", "type": "travel"},
        {"youtube_video_id": "o26qoCYLdS8", "title": "Relaxing Jazz Instrumental Music For Study, Work, Relax", "type": "music"},
        {"youtube_video_id": "OKHSQveDPMk", "title": "Beautiful Relaxing Ambient Music - Relax, Stress Relief, Sleep", "type": "music"},
        {"youtube_video_id": "RIIJgWC6rFs", "title": "Gentle Low Impact All-in-One Exercises for Seniors | 30 min", "type": "exercise"},
        {"youtube_video_id": "Z26PWsBsSFY", "title": "Walk at home - Walking Workout for Seniors & Beginners", "type": "exercise"},
        {"youtube_video_id": "bO6NNfX_1ns", "title": "10-minute Indoor Walking Workout for Seniors, Beginner", "type": "exercise"},
        {"youtube_video_id": "HP_P-A3crw4", "title": "20 minute Low Impact Cardio Workout for Seniors and Beginners", "type": "exercise"},
    ],
    "Fear": [
        {"youtube_video_id": "LomAPbJ6Huk", "title": "Grounding Meditation Safe Place", "type": "meditation"},
        {"youtube_video_id": "spUPtRwLmvM", "title": "9 Minute Grounding Stop Panic", "type": "meditation"},
        {"youtube_video_id": "VVCf9JABRLk", "title": "Guided Meditation Panic Attacks", "type": "meditation"},
        {"youtube_video_id": "aNXKjGFUlMs", "title": "Deep Breathing for Anxiety", "type": "breathing"},
        {"youtube_video_id": "UfcAVejslrU", "title": "Grounding Nature Therapy", "type": "nature"},
        {"youtube_video_id": "0E99NqV0wI8", "title": "Calming Music for Panic", "type": "music"},
        {"youtube_video_id": "VqVkTFLcwpQ", "title": "Safe Space Visualization", "type": "meditation"},
        {"youtube_video_id": "2G8LAiHSCAs", "title": "Forest Birdsong Nature Sounds", "type": "nature"},
        {"youtube_video_id": "P3uFPd7eDTs", "title": "Managing Panic Attacks 10-Min", "type": "meditation"},
        {"youtube_video_id": "iLzMl3LT8GY", "title": "Let Go of Fear", "type": "meditation"},
        {"youtube_video_id": "ccVKymvUD-4", "title": "Grounding Techniques CALM", "type": "breathing"},
        {"youtube_video_id": "uLFN3cJ9Nyw", "title": "Meditation Anxiety Panic", "type": "meditation"},
        {"youtube_video_id": "NG-qzDFv-Ek", "title": "Overcome Fear Anxiety Gurudev", "type": "meditation"},
        {"youtube_video_id": "1E3ytLd7uJA", "title": "Bible Verses for Anxiety and Worry - Calm Scriptures & Nature Sounds", "type": "spiritual"},
        {"youtube_video_id": "O-6f5wQXSu8", "title": "10-Minute Meditation For Anxiety | Goodful", "type": "meditation"},
        {"youtube_video_id": "rPQseuVXGSU", "title": "Timeless Classical Music for Seniors: Boost Memory, Soothe Anxiety", "type": "music"},
        {"youtube_video_id": "716XlBUCJCA", "title": "Inspirational Quotes for a Fulfilling Life After 60", "type": "inspirational"},
        {"youtube_video_id": "lGr73xZ-S7s", "title": "Aging is My Super Power | Rita Moore | TEDxGreensboro", "type": "inspirational"},
        {"youtube_video_id": "yqKOjo34Cho", "title": "Seniors Stories For Sleep - Inspired Story for Adults", "type": "story"},
        {"youtube_video_id": "xu84bbTu7ak", "title": "The BEST Sleepy Stories EVER | Alexandra Turney", "type": "story"},
    ],
    "Surprise": [
        {"youtube_video_id": "E1QERTHF-7c", "title": "Guided Visualization Inner Peace", "type": "meditation"},
        {"youtube_video_id": "UqYozgCGIgk", "title": "Visualization Imagery Inner Peace", "type": "meditation"},
        {"youtube_video_id": "yptJja6KB8U", "title": "Magical Forest Meditation", "type": "meditation"},
        {"youtube_video_id": "Lzvj_JVZkzY", "title": "Meditation Seniors Mindfulness", "type": "meditation"},
        {"youtube_video_id": "DH7Aq-Sl6C0", "title": "Gentle Yoga Stretch Beginners", "type": "yoga"},
        {"youtube_video_id": "HlfPKF051q8", "title": "Yoga Therapy Neuroplasticity", "type": "yoga"},
        {"youtube_video_id": "MxAfZ_N_HH4", "title": "30mins Gentle Tai Chi Seniors", "type": "taichi"},
        {"youtube_video_id": "XudcUGbs5HM", "title": "TAI CHI BALANCE Seniors", "type": "taichi"},
        {"youtube_video_id": "3pxjTR83MVU", "title": "Build Courage Strength Meditation", "type": "meditation"},
        {"youtube_video_id": "YzsE5oVtrk0", "title": "Meditation Confidence Courage", "type": "meditation"},
        {"youtube_video_id": "1lD0HdR9zA8", "title": "Self-Confidence Strong", "type": "meditation"},
        {"youtube_video_id": "tY3NnodM3Ww", "title": "Loving Kindness Metta Meditation", "type": "meditation"},
        {"youtube_video_id": "716XlBUCJCA", "title": "Inspirational Quotes for a Fulfilling Life After 60", "type": "inspirational"},
        {"youtube_video_id": "lGr73xZ-S7s", "title": "Aging is My Super Power | Rita Moore | TEDxGreensboro", "type": "inspirational"},
        {"youtube_video_id": "bnpjhm4pmnQ", "title": "The 5 things seniors must rely on instead of family for", "type": "inspirational"},
        {"youtube_video_id": "MWoS9oFJIzY", "title": "Older Man Talks About How to Create a Life of Purpose", "type": "inspirational"},
    ],
    "Disgust": [
        {"youtube_video_id": "aEqlQvczMJQ", "title": "Renewal Meditation", "type": "meditation"},
        {"youtube_video_id": "qH0zNiCgO9o", "title": "Fresh Nature Scenery", "type": "nature"},
        {"youtube_video_id": "2OEL4P1Rz04", "title": "Cleansing Music Therapy", "type": "music"},
        {"youtube_video_id": "aNXKjGFUlMs", "title": "Purifying Breath Work", "type": "breathing"},
        {"youtube_video_id": "UqYozgCGIgk", "title": "Cleansing Visualization", "type": "meditation"},
        {"youtube_video_id": "Aq6NVQSlxrw", "title": "Fresh Forest Morning Sounds", "type": "nature"},
        {"youtube_video_id": "2G8LAiHSCAs", "title": "Forest Birdsong Clarity", "type": "nature"},
        {"youtube_video_id": "HchoJcYNYlU", "title": "Waterfall Cleansing Water", "type": "nature"},
        {"youtube_video_id": "mudV-JLllnI", "title": "432 Hz 7 CHAKRAS Aura Cleanse", "type": "music"},
        {"youtube_video_id": "eu6iRyyq3u0", "title": "432 Hz CHAKRAS HEALING", "type": "music"},
        {"youtube_video_id": "gBXG0obrSs4", "title": "Throat Chakra Healing 192Hz", "type": "music"},
        {"youtube_video_id": "aX2Aq7aQMGg", "title": "Solar Plexus Chakra Confidence", "type": "meditation"},
        {"youtube_video_id": "d4Cn5NRw8Ro", "title": "Root Chakra Meditation", "type": "meditation"},
        {"youtube_video_id": "8mWe1AMK2J8", "title": "741 Hz Remove Toxins Throat", "type": "music"},
        {"youtube_video_id": "6gK2adsP2Xo", "title": "Chakra Meditation Grounding", "type": "meditation"},
        {"youtube_video_id": "5XMtjE_TCbM", "title": "Confidence Power Plexus Yoga", "type": "yoga"},
        {"youtube_video_id": "cKGaHAxXCBg", "title": "Root Chakra Grounding Strength", "type": "meditation"},
    ],
}
