"""initial_schema

Revision ID: f9148a721195
Revises: 
Create Date: 2026-03-25 14:50:51.005946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9148a721195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('encrypted_text', sa.Text(), nullable=True),
    sa.Column('prediction_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('review_request_id', sa.String(length=100), nullable=True),
    sa.Column('consent_token', sa.Text(), nullable=True),
    sa.Column('training_eligible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_user_created', 'analysis_records', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_analysis_user_label', 'analysis_records', ['user_id', 'prediction_label'], unique=False)
    op.create_index(op.f('ix_analysis_records_created_at'), 'analysis_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_records_prediction_label'), 'analysis_records', ['prediction_label'], unique=False)
    op.create_index(op.f('ix_analysis_records_request_id'), 'analysis_records', ['request_id'], unique=True)
    op.create_index(op.f('ix_analysis_records_requires_human_review'), 'analysis_records', ['requires_human_review'], unique=False)
    op.create_index(op.f('ix_analysis_records_review_request_id'), 'analysis_records', ['review_request_id'], unique=False)
    op.create_index(op.f('ix_analysis_records_training_eligible'), 'analysis_records', ['training_eligible'], unique=False)
    op.create_index(op.f('ix_analysis_records_user_id'), 'analysis_records', ['user_id'], unique=False)
    op.create_table('assessment_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('assessment_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assess_req_doctor_patient', 'assessment_requests', ['doctor_id', 'patient_id'], unique=False)
    op.create_index('idx_assess_req_patient_status', 'assessment_requests', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_assessment_requests_assessment_type'), 'assessment_requests', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessment_requests_created_at'), 'assessment_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessment_requests_doctor_id'), 'assessment_requests', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_assessment_requests_expires_at'), 'assessment_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_assessment_requests_patient_id'), 'assessment_requests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_assessment_requests_request_id'), 'assessment_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_assessment_requests_status'), 'assessment_requests', ['status'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('assessment_type', sa.String(length=10), nullable=False),
    sa.Column('assessment_request_id', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=False),
    sa.Column('severity_label', sa.String(length=100), nullable=False),
    sa.Column('treatment_recommendations', sa.JSON(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('visible_to_patient', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assess_request_id', 'assessments', ['assessment_request_id'], unique=False)
    op.create_index('idx_assess_user_date', 'assessments', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_assess_user_type_date', 'assessments', ['user_id', 'assessment_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_id'), 'assessments', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_assessments_assessment_request_id'), 'assessments', ['assessment_request_id'], unique=False)
    op.create_index(op.f('ix_assessments_assessment_type'), 'assessments', ['assessment_type'], unique=False)
    op.create_index(op.f('ix_assessments_created_at'), 'assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessments_severity_level'), 'assessments', ['severity_level'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('audio_analysis_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('dominant_emotion_ai', sa.String(length=50), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('dominant_emotion_human', sa.String(length=50), nullable=True),
    sa.Column('emotional_patterns', sa.JSON(), nullable=True),
    sa.Column('clinical_insights', sa.JSON(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_review_session', 'audio_analysis_reviews', ['session_id'], unique=False)
    op.create_index('idx_audio_review_status', 'audio_analysis_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_audio_analysis_reviews_created_at'), 'audio_analysis_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_analysis_reviews_review_id'), 'audio_analysis_reviews', ['review_id'], unique=True)
    op.create_index(op.f('ix_audio_analysis_reviews_reviewer_id'), 'audio_analysis_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_audio_analysis_reviews_session_id'), 'audio_analysis_reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_audio_analysis_reviews_status'), 'audio_analysis_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_audio_analysis_reviews_user_id'), 'audio_analysis_reviews', ['user_id'], unique=False)
    op.create_table('audio_analysis_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('audio_quality_score', sa.Float(), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('review_request_id', sa.String(length=100), nullable=True),
    sa.Column('session_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('audio_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audio_sess_user_created', 'audio_analysis_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audio_analysis_sessions_created_at'), 'audio_analysis_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_analysis_sessions_review_request_id'), 'audio_analysis_sessions', ['review_request_id'], unique=False)
    op.create_index(op.f('ix_audio_analysis_sessions_session_id'), 'audio_analysis_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_audio_analysis_sessions_status'), 'audio_analysis_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_audio_analysis_sessions_user_id'), 'audio_analysis_sessions', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('doctor_code', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_code', name='uq_doctor_code'),
    sa.UniqueConstraint('email', name='uq_doctor_email')
    )
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_doctor_code'), 'doctors', ['doctor_code'], unique=True)
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=True)
    op.create_index(op.f('ix_doctors_specialty'), 'doctors', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctors_verification_status'), 'doctors', ['verification_status'], unique=False)
    op.create_table('emergency_alert_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('doctor_notified', sa.Boolean(), nullable=False),
    sa.Column('loved_one_notified', sa.Boolean(), nullable=False),
    sa.Column('emergency_condition', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('alert_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emerg_alert_user_status', 'emergency_alert_logs', ['user_id', 'alert_status'], unique=False)
    op.create_index('idx_emerg_alert_user_time', 'emergency_alert_logs', ['user_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_emergency_alert_logs_alert_status'), 'emergency_alert_logs', ['alert_status'], unique=False)
    op.create_index(op.f('ix_emergency_alert_logs_alert_type'), 'emergency_alert_logs', ['alert_type'], unique=False)
    op.create_index(op.f('ix_emergency_alert_logs_triggered_at'), 'emergency_alert_logs', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_emergency_alert_logs_user_id'), 'emergency_alert_logs', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('doctor_enabled', sa.Boolean(), nullable=False),
    sa.Column('doctor_email', sa.String(length=255), nullable=True),
    sa.Column('loved_one_enabled', sa.Boolean(), nullable=False),
    sa.Column('loved_one_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_created_at'), 'emergency_contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=True)
    op.create_table('health_metrics_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('oxygen_level', sa.Float(), nullable=True),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('pulse_rate', sa.Integer(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_user_date', 'health_metrics_entries', ['user_id', 'date'], unique=False)
    op.create_index('idx_health_user_timestamp', 'health_metrics_entries', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_health_metrics_entries_created_at'), 'health_metrics_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_health_metrics_entries_date'), 'health_metrics_entries', ['date'], unique=False)
    op.create_index(op.f('ix_health_metrics_entries_entry_id'), 'health_metrics_entries', ['entry_id'], unique=True)
    op.create_index(op.f('ix_health_metrics_entries_risk_level'), 'health_metrics_entries', ['risk_level'], unique=False)
    op.create_index(op.f('ix_health_metrics_entries_timestamp'), 'health_metrics_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_health_metrics_entries_user_id'), 'health_metrics_entries', ['user_id'], unique=False)
    op.create_table('mental_wellness_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('form_date', sa.Date(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('ai_summary_clinical', sa.Text(), nullable=True),
    sa.Column('ai_summary_patient', sa.Text(), nullable=True),
    sa.Column('ai_patterns_detected', sa.JSON(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('ai_generation_status', sa.String(length=50), nullable=False),
    sa.Column('ai_error_message', sa.Text(), nullable=True),
    sa.Column('ai_summary_version', sa.Integer(), nullable=False),
    sa.Column('ai_regenerated_count', sa.Integer(), nullable=False),
    sa.Column('form_data_hash', sa.String(length=64), nullable=True),
    sa.Column('ai_report_status', sa.String(length=50), nullable=False),
    sa.Column('ai_report_sent_at', sa.DateTime(), nullable=True),
    sa.Column('ai_report_sent_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_well_form_doctor_user_status', 'mental_wellness_forms', ['doctor_id', 'user_id', 'status'], unique=False)
    op.create_index('idx_well_form_user_ai_status', 'mental_wellness_forms', ['user_id', 'ai_generation_status', 'form_date'], unique=False)
    op.create_index('idx_well_form_user_status_date', 'mental_wellness_forms', ['user_id', 'status', 'form_date'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_ai_generation_status'), 'mental_wellness_forms', ['ai_generation_status'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_ai_report_status'), 'mental_wellness_forms', ['ai_report_status'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_created_at'), 'mental_wellness_forms', ['created_at'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_doctor_id'), 'mental_wellness_forms', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_form_data_hash'), 'mental_wellness_forms', ['form_data_hash'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_form_date'), 'mental_wellness_forms', ['form_date'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_form_id'), 'mental_wellness_forms', ['form_id'], unique=True)
    op.create_index(op.f('ix_mental_wellness_forms_status'), 'mental_wellness_forms', ['status'], unique=False)
    op.create_index(op.f('ix_mental_wellness_forms_user_id'), 'mental_wellness_forms', ['user_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_id', sa.String(length=100), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('fine_tuned', sa.Boolean(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_created_at'), 'model_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_version_id'), 'model_versions', ['version_id'], unique=True)
    op.create_table('mood_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_mood_user_date')
    )
    op.create_index('idx_mood_user_date', 'mood_entries', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_mood_entries_created_at'), 'mood_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_mood_entries_date'), 'mood_entries', ['date'], unique=False)
    op.create_index(op.f('ix_mood_entries_entry_id'), 'mood_entries', ['entry_id'], unique=True)
    op.create_index(op.f('ix_mood_entries_user_id'), 'mood_entries', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('doctor_id', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_doctor_read_created', 'notifications', ['doctor_id', 'read', 'created_at'], unique=False)
    op.create_index('idx_notif_user_read_created', 'notifications', ['user_id', 'read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_doctor_id'), 'notifications', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('recommendation_play_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('emotion_category', sa.String(length=100), nullable=False),
    sa.Column('media_key', sa.String(length=255), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'emotion_category', 'media_type', 'media_key', name='uq_rec_history_user_emotion_media_key')
    )
    op.create_index('idx_rec_history_user_played', 'recommendation_play_history', ['user_id', 'played_at'], unique=False)
    op.create_index(op.f('ix_recommendation_play_history_emotion_category'), 'recommendation_play_history', ['emotion_category'], unique=False)
    op.create_index(op.f('ix_recommendation_play_history_media_type'), 'recommendation_play_history', ['media_type'], unique=False)
    op.create_index(op.f('ix_recommendation_play_history_played_at'), 'recommendation_play_history', ['played_at'], unique=False)
    op.create_index(op.f('ix_recommendation_play_history_user_id'), 'recommendation_play_history', ['user_id'], unique=False)
    op.create_table('recommendation_session_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('emotion_category', sa.String(length=100), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('chosen_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', 'emotion_category', 'media_type', name='uq_rec_cache_user_session_emotion_media')
    )
    op.create_index('idx_rec_cache_expires_at', 'recommendation_session_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_recommendation_session_cache_created_at'), 'recommendation_session_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_session_cache_emotion_category'), 'recommendation_session_cache', ['emotion_category'], unique=False)
    op.create_index(op.f('ix_recommendation_session_cache_expires_at'), 'recommendation_session_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_recommendation_session_cache_session_id'), 'recommendation_session_cache', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendation_session_cache_user_id'), 'recommendation_session_cache', ['user_id'], unique=False)
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('original_prediction', sa.String(length=50), nullable=False),
    sa.Column('human_assessment', sa.String(length=50), nullable=False),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_status_created', 'review_records', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_review_records_created_at'), 'review_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_records_request_id'), 'review_records', ['request_id'], unique=False)
    op.create_index(op.f('ix_review_records_review_id'), 'review_records', ['review_id'], unique=True)
    op.create_index(op.f('ix_review_records_reviewer_id'), 'review_records', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_records_status'), 'review_records', ['status'], unique=False)
    op.create_index(op.f('ix_review_records_user_id'), 'review_records', ['user_id'], unique=False)
    op.create_table('user_doctor_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('doctor_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('connection_method', sa.String(length=50), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'doctor_id', name='uq_user_doctor')
    )
    op.create_index('idx_user_doctor_rel_doctor_status', 'user_doctor_relationships', ['doctor_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_doctor_relationships_doctor_id'), 'user_doctor_relationships', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_user_doctor_relationships_status'), 'user_doctor_relationships', ['status'], unique=False)
    op.create_index(op.f('ix_user_doctor_relationships_user_id'), 'user_doctor_relationships', ['user_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('original_request_id', sa.String(length=100), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_created_at'), 'user_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_feedback_feedback_id'), 'user_feedback', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_user_feedback_feedback_type'), 'user_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_user_feedback_original_request_id'), 'user_feedback', ['original_request_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('fontSize', sa.String(length=20), nullable=False),
    sa.Column('highContrast', sa.Boolean(), nullable=False),
    sa.Column('reduceMotion', sa.Boolean(), nullable=False),
    sa.Column('textToSpeech', sa.Boolean(), nullable=False),
    sa.Column('autoSave', sa.Boolean(), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_created_at'), 'user_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_profile_email')
    )
    op.create_index(op.f('ix_user_profiles_created_at'), 'user_profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('video_analysis_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('dominant_emotion_ai', sa.String(length=50), nullable=False),
    sa.Column('dominant_emotion_human', sa.String(length=50), nullable=True),
    sa.Column('emotional_patterns', sa.JSON(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('confidence_override', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_review_session', 'video_analysis_reviews', ['session_id'], unique=False)
    op.create_index('idx_video_review_status', 'video_analysis_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_video_analysis_reviews_created_at'), 'video_analysis_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_analysis_reviews_review_id'), 'video_analysis_reviews', ['review_id'], unique=True)
    op.create_index(op.f('ix_video_analysis_reviews_reviewer_id'), 'video_analysis_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_video_analysis_reviews_session_id'), 'video_analysis_reviews', ['session_id'], unique=False)
    op.create_index(op.f('ix_video_analysis_reviews_status'), 'video_analysis_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_video_analysis_reviews_user_id'), 'video_analysis_reviews', ['user_id'], unique=False)
    op.create_table('video_analysis_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=True),
    sa.Column('requires_human_review', sa.Boolean(), nullable=True),
    sa.Column('review_request_id', sa.String(length=100), nullable=True),
    sa.Column('session_file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_sess_user_created', 'video_analysis_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_video_analysis_sessions_created_at'), 'video_analysis_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_analysis_sessions_review_request_id'), 'video_analysis_sessions', ['review_request_id'], unique=False)
    op.create_index(op.f('ix_video_analysis_sessions_session_id'), 'video_analysis_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_video_analysis_sessions_status'), 'video_analysis_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_video_analysis_sessions_user_id'), 'video_analysis_sessions', ['user_id'], unique=False)
    op.create_table('video_frame_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frame_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('emotion_detected', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('face_detected', sa.Boolean(), nullable=True),
    sa.Column('frame_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_frame_session', 'video_frame_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_video_frame_records_frame_id'), 'video_frame_records', ['frame_id'], unique=True)
    op.create_index(op.f('ix_video_frame_records_session_id'), 'video_frame_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_frame_records_session_id'), table_name='video_frame_records')
    op.drop_index(op.f('ix_video_frame_records_frame_id'), table_name='video_frame_records')
    op.drop_index('idx_video_frame_session', table_name='video_frame_records')
    op.drop_table('video_frame_records')
    op.drop_index(op.f('ix_video_analysis_sessions_user_id'), table_name='video_analysis_sessions')
    op.drop_index(op.f('ix_video_analysis_sessions_status'), table_name='video_analysis_sessions')
    op.drop_index(op.f('ix_video_analysis_sessions_session_id'), table_name='video_analysis_sessions')
    op.drop_index(op.f('ix_video_analysis_sessions_review_request_id'), table_name='video_analysis_sessions')
    op.drop_index(op.f('ix_video_analysis_sessions_created_at'), table_name='video_analysis_sessions')
    op.drop_index('idx_video_sess_user_created', table_name='video_analysis_sessions')
    op.drop_table('video_analysis_sessions')
    op.drop_index(op.f('ix_video_analysis_reviews_user_id'), table_name='video_analysis_reviews')
    op.drop_index(op.f('ix_video_analysis_reviews_status'), table_name='video_analysis_reviews')
    op.drop_index(op.f('ix_video_analysis_reviews_session_id'), table_name='video_analysis_reviews')
    op.drop_index(op.f('ix_video_analysis_reviews_reviewer_id'), table_name='video_analysis_reviews')
    op.drop_index(op.f('ix_video_analysis_reviews_review_id'), table_name='video_analysis_reviews')
    op.drop_index(op.f('ix_video_analysis_reviews_created_at'), table_name='video_analysis_reviews')
    op.drop_index('idx_video_review_status', table_name='video_analysis_reviews')
    op.drop_index('idx_video_review_session', table_name='video_analysis_reviews')
    op.drop_table('video_analysis_reviews')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_created_at'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_created_at'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_original_request_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_type'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_feedback_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_created_at'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_user_doctor_relationships_user_id'), table_name='user_doctor_relationships')
    op.drop_index(op.f('ix_user_doctor_relationships_status'), table_name='user_doctor_relationships')
    op.drop_index(op.f('ix_user_doctor_relationships_doctor_id'), table_name='user_doctor_relationships')
    op.drop_index('idx_user_doctor_rel_doctor_status', table_name='user_doctor_relationships')
    op.drop_table('user_doctor_relationships')
    op.drop_index(op.f('ix_review_records_user_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_status'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_reviewer_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_review_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_request_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_created_at'), table_name='review_records')
    op.drop_index('idx_review_status_created', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index(op.f('ix_recommendation_session_cache_user_id'), table_name='recommendation_session_cache')
    op.drop_index(op.f('ix_recommendation_session_cache_session_id'), table_name='recommendation_session_cache')
    op.drop_index(op.f('ix_recommendation_session_cache_expires_at'), table_name='recommendation_session_cache')
    op.drop_index(op.f('ix_recommendation_session_cache_emotion_category'), table_name='recommendation_session_cache')
    op.drop_index(op.f('ix_recommendation_session_cache_created_at'), table_name='recommendation_session_cache')
    op.drop_index('idx_rec_cache_expires_at', table_name='recommendation_session_cache')
    op.drop_table('recommendation_session_cache')
    op.drop_index(op.f('ix_recommendation_play_history_user_id'), table_name='recommendation_play_history')
    op.drop_index(op.f('ix_recommendation_play_history_played_at'), table_name='recommendation_play_history')
    op.drop_index(op.f('ix_recommendation_play_history_media_type'), table_name='recommendation_play_history')
    op.drop_index(op.f('ix_recommendation_play_history_emotion_category'), table_name='recommendation_play_history')
    op.drop_index('idx_rec_history_user_played', table_name='recommendation_play_history')
    op.drop_table('recommendation_play_history')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_doctor_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notif_user_read_created', table_name='notifications')
    op.drop_index('idx_notif_doctor_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mood_entries_user_id'), table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_entry_id'), table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_date'), table_name='mood_entries')
    op.drop_index(op.f('ix_mood_entries_created_at'), table_name='mood_entries')
    op.drop_index('idx_mood_user_date', table_name='mood_entries')
    op.drop_table('mood_entries')
    op.drop_index(op.f('ix_model_versions_version_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_created_at'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_mental_wellness_forms_user_id'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_status'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_form_id'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_form_date'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_form_data_hash'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_doctor_id'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_created_at'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_ai_report_status'), table_name='mental_wellness_forms')
    op.drop_index(op.f('ix_mental_wellness_forms_ai_generation_status'), table_name='mental_wellness_forms')
    op.drop_index('idx_well_form_user_status_date', table_name='mental_wellness_forms')
    op.drop_index('idx_well_form_user_ai_status', table_name='mental_wellness_forms')
    op.drop_index('idx_well_form_doctor_user_status', table_name='mental_wellness_forms')
    op.drop_table('mental_wellness_forms')
    op.drop_index(op.f('ix_health_metrics_entries_user_id'), table_name='health_metrics_entries')
    op.drop_index(op.f('ix_health_metrics_entries_timestamp'), table_name='health_metrics_entries')
    op.drop_index(op.f('ix_health_metrics_entries_risk_level'), table_name='health_metrics_entries')
    op.drop_index(op.f('ix_health_metrics_entries_entry_id'), table_name='health_metrics_entries')
    op.drop_index(op.f('ix_health_metrics_entries_date'), table_name='health_metrics_entries')
    op.drop_index(op.f('ix_health_metrics_entries_created_at'), table_name='health_metrics_entries')
    op.drop_index('idx_health_user_timestamp', table_name='health_metrics_entries')
    op.drop_index('idx_health_user_date', table_name='health_metrics_entries')
    op.drop_table('health_metrics_entries')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_created_at'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_emergency_alert_logs_user_id'), table_name='emergency_alert_logs')
    op.drop_index(op.f('ix_emergency_alert_logs_triggered_at'), table_name='emergency_alert_logs')
    op.drop_index(op.f('ix_emergency_alert_logs_alert_type'), table_name='emergency_alert_logs')
    op.drop_index(op.f('ix_emergency_alert_logs_alert_status'), table_name='emergency_alert_logs')
    op.drop_index('idx_emerg_alert_user_time', table_name='emergency_alert_logs')
    op.drop_index('idx_emerg_alert_user_status', table_name='emergency_alert_logs')
    op.drop_table('emergency_alert_logs')
    op.drop_index(op.f('ix_doctors_verification_status'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialty'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_code'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_audio_analysis_sessions_user_id'), table_name='audio_analysis_sessions')
    op.drop_index(op.f('ix_audio_analysis_sessions_status'), table_name='audio_analysis_sessions')
    op.drop_index(op.f('ix_audio_analysis_sessions_session_id'), table_name='audio_analysis_sessions')
    op.drop_index(op.f('ix_audio_analysis_sessions_review_request_id'), table_name='audio_analysis_sessions')
    op.drop_index(op.f('ix_audio_analysis_sessions_created_at'), table_name='audio_analysis_sessions')
    op.drop_index('idx_audio_sess_user_created', table_name='audio_analysis_sessions')
    op.drop_table('audio_analysis_sessions')
    op.drop_index(op.f('ix_audio_analysis_reviews_user_id'), table_name='audio_analysis_reviews')
    op.drop_index(op.f('ix_audio_analysis_reviews_status'), table_name='audio_analysis_reviews')
    op.drop_index(op.f('ix_audio_analysis_reviews_session_id'), table_name='audio_analysis_reviews')
    op.drop_index(op.f('ix_audio_analysis_reviews_reviewer_id'), table_name='audio_analysis_reviews')
    op.drop_index(op.f('ix_audio_analysis_reviews_review_id'), table_name='audio_analysis_reviews')
    op.drop_index(op.f('ix_audio_analysis_reviews_created_at'), table_name='audio_analysis_reviews')
    op.drop_index('idx_audio_review_status', table_name='audio_analysis_reviews')
    op.drop_index('idx_audio_review_session', table_name='audio_analysis_reviews')
    op.drop_table('audio_analysis_reviews')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_severity_level'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_at'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_type'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_request_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_assessment_id'), table_name='assessments')
    op.drop_index('idx_assess_user_type_date', table_name='assessments')
    op.drop_index('idx_assess_user_date', table_name='assessments')
    op.drop_index('idx_assess_request_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_assessment_requests_status'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_request_id'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_patient_id'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_expires_at'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_doctor_id'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_created_at'), table_name='assessment_requests')
    op.drop_index(op.f('ix_assessment_requests_assessment_type'), table_name='assessment_requests')
    op.drop_index('idx_assess_req_patient_status', table_name='assessment_requests')
    op.drop_index('idx_assess_req_doctor_patient', table_name='assessment_requests')
    op.drop_table('assessment_requests')
    op.drop_index(op.f('ix_analysis_records_user_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_training_eligible'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_review_request_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_requires_human_review'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_request_id'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_prediction_label'), table_name='analysis_records')
    op.drop_index(op.f('ix_analysis_records_created_at'), table_name='analysis_records')
    op.drop_index('idx_analysis_user_label', table_name='analysis_records')
    op.drop_index('idx_analysis_user_created', table_name='analysis_records')
    op.drop_table('analysis_records')
    # ### end Alembic commands ###
